/**
 * wake_word.c
 * Wake Word Detection Engine
 *
 * Model:  DS-CNN-S (Depthwise-Separable CNN, Keyword Spotting)
 *         Input:  40 log-mel filterbank features × 98 time frames (INT8)
 *         Output: 10-class softmax (hey_nitch, quicknitch, + 8 non-target)
 *         Size:   ~42KB INT8 quantized TFLite flatbuffer
 *
 * Implementation: TensorFlow Lite for Microcontrollers (TFLM) on ARM core.
 * Audio path: PDM → CIC decimation → 16kHz PCM → STFT → log-mel → CNN.
 *
 * Power: PDM always on (2mW), ARM core active @ reduced clock during STFT,
 *        inference on ARM (no HW-AccAI — model too small to justify DMA cost).
 */

#include "wake_word.h"
#include "hal.h"
#include <math.h>

/* ─────────────────────────────────────────────
   TFLM integration
   In the real build these come from tensorflow/lite/micro headers.
   Here we declare the minimum needed types so the logic compiles.
   ───────────────────────────────────────────── */
#ifdef TFLM_AVAILABLE
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/micro/kernels/micro_ops.h"
#else
/* Stub types for compilation without TFLM headers */
typedef void* TfLiteInterpreter;
typedef struct { int8_t *data; } TfLiteTensor;
#endif

/* ─────────────────────────────────────────────
   Model (TFLite flatbuffer as C array)
   Generated via: xxd -i wake_word_int8.tflite > wake_word_model.h
   ───────────────────────────────────────────── */
#include "models/wake_word_model.h"   /* extern const uint8_t g_wake_word_model[]; */
                                       /* extern const uint32_t g_wake_word_model_size; */

/* ─────────────────────────────────────────────
   TFLM tensor arena
   DS-CNN-S requires ~20KB working memory
   ───────────────────────────────────────────── */
#define TFLM_ARENA_SIZE  (24U * 1024U)
static uint8_t s_tflm_arena[TFLM_ARENA_SIZE] __attribute__((aligned(16)));

/* ─────────────────────────────────────────────
   Mel filterbank constants
   40 filters, 512-point FFT, 16kHz sample rate, 25ms window, 10ms hop
   ───────────────────────────────────────────── */
#define FFT_SIZE          512U
#define HOP_SAMPLES       160U   /* 10ms @ 16kHz */
#define WIN_SAMPLES       400U   /* 25ms @ 16kHz */
#define N_MEL             40U
#define N_FRAMES          98U

/* Hann window (pre-computed, Q15 fixed-point) */
static const int16_t s_hann_win[WIN_SAMPLES];  /* generated at init */

/* Mel filterbank weights: 40 filters × (FFT_SIZE/2+1=257) bins
 * Stored as Q8 (uint8) weight + start/end bin index per filter
 * Full table omitted for brevity — generated by Python script.       */
typedef struct { uint16_t start; uint16_t end; } mel_filter_t;
static mel_filter_t s_mel_filters[N_MEL];

/* INT8 quantization params for the mel input tensor */
#define MEL_QUANT_SCALE   0.00392157f   /* 1/255 */
#define MEL_QUANT_ZERO    -128

/* ─────────────────────────────────────────────
   Sliding window PCM buffer
   ───────────────────────────────────────────── */
static int16_t s_pcm_window[WIN_SAMPLES];
static int32_t s_pcm_ring_pos = 0;   /* how many new samples since last hop */

/* INT8 mel spectrogram: [N_FRAMES][N_MEL] */
static int8_t  s_mel_input[N_FRAMES * N_MEL];
static uint8_t s_frame_idx = 0;

/* ─────────────────────────────────────────────
   Fixed-point FFT (bit-reversal + Cooley-Tukey)
   We use a compact radix-2 DIT FFT on int32 arrays.
   ───────────────────────────────────────────── */
#define LOG2_FFT  9U   /* log2(512) */

/* Bit-reversal table for 512-point (pre-computed) */
static const uint16_t s_bit_rev[FFT_SIZE]; /* generated at init */

/* Twiddle factors (cos, sin) as Q15 */
static int16_t s_tw_cos[FFT_SIZE / 2];
static int16_t s_tw_sin[FFT_SIZE / 2];

static void fft_init(void) {
    /* Build twiddle factors */
    for (uint32_t k = 0; k < FFT_SIZE / 2; k++) {
        float angle = -2.0f * 3.14159265f * (float)k / (float)FFT_SIZE;
        s_tw_cos[k] = (int16_t)(cosf(angle) * 32767.0f);
        s_tw_sin[k] = (int16_t)(sinf(angle) * 32767.0f);
    }
}

/* Compute |FFT|^2 for WIN_SAMPLES of int16 input
 * dst: FFT_SIZE/2+1 power spectrum values (int32) */
static void compute_power_spectrum(
        const int16_t *pcm,
        int32_t       *power_out) {

    /* Zero-pad to FFT_SIZE */
    int32_t re[FFT_SIZE], im[FFT_SIZE];
    for (uint32_t i = 0; i < FFT_SIZE; i++) {
        if (i < WIN_SAMPLES) {
            re[i] = ((int32_t)pcm[i] * s_hann_win[i]) >> 15;
        } else {
            re[i] = 0;
        }
        im[i] = 0;
    }

    /* Radix-2 DIT FFT (fixed-point, abbreviated — real production would
     * use an optimised ARM CMSIS-DSP arm_cfft_q15 call for efficiency) */
    uint32_t half = FFT_SIZE;
    for (uint32_t stage = 0; stage < LOG2_FFT; stage++) {
        half >>= 1;
        uint32_t tw_step = (FFT_SIZE / 2) >> stage;
        for (uint32_t j = 0; j < FFT_SIZE; j += (half << 1)) {
            for (uint32_t k = 0; k < half; k++) {
                uint32_t tw_idx = k * tw_step;
                int32_t  wr = s_tw_cos[tw_idx];
                int32_t  wi = s_tw_sin[tw_idx];
                uint32_t p  = j + k;
                uint32_t q  = p + half;
                int32_t  tr = (wr * re[q] - wi * im[q]) >> 15;
                int32_t  ti = (wr * im[q] + wi * re[q]) >> 15;
                re[q]  = re[p] - tr;
                im[q]  = im[p] - ti;
                re[p] += tr;
                im[p] += ti;
            }
        }
    }

    /* Power spectrum: |X[k]|^2 for k=0..N/2 */
    for (uint32_t k = 0; k <= FFT_SIZE / 2; k++) {
        int32_t r = re[k] >> 8;
        int32_t i = im[k] >> 8;
        power_out[k] = r*r + i*i;
    }
}

/* ─────────────────────────────────────────────
   Mel filterbank application
   ───────────────────────────────────────────── */
static void build_mel_filters(void) {
    /* Map 40 mel-scale bands between 80Hz and 7600Hz in 16kHz/512-point FFT */
    float f_low  = 80.0f;
    float f_high = 7600.0f;
    float mel_low  = 2595.0f * log10f(1.0f + f_low  / 700.0f);
    float mel_high = 2595.0f * log10f(1.0f + f_high / 700.0f);
    float mel_step = (mel_high - mel_low) / (N_MEL + 1);

    for (uint32_t m = 0; m < N_MEL; m++) {
        float mel_c   = mel_low + (m + 1) * mel_step;
        float f_c     = 700.0f * (powf(10.0f, mel_c / 2595.0f) - 1.0f);
        float mel_l   = mel_c - mel_step;
        float mel_r   = mel_c + mel_step;
        float f_l     = 700.0f * (powf(10.0f, mel_l / 2595.0f) - 1.0f);
        float f_r     = 700.0f * (powf(10.0f, mel_r / 2595.0f) - 1.0f);
        /* Convert to FFT bin indices */
        s_mel_filters[m].start = (uint16_t)(f_l * FFT_SIZE / 16000.0f);
        s_mel_filters[m].end   = (uint16_t)(f_r * FFT_SIZE / 16000.0f);
        (void)f_c;
    }
}

static void apply_mel_filterbank(const int32_t *power, float *mel_out) {
    for (uint32_t m = 0; m < N_MEL; m++) {
        float sum = 0.0f;
        for (uint32_t b = s_mel_filters[m].start; b <= s_mel_filters[m].end; b++) {
            sum += (float)power[b];
        }
        /* log(sum + epsilon) */
        mel_out[m] = logf(sum + 1e-6f);
    }
}

static void mel_to_int8(const float *mel_float, int8_t *mel_int8) {
    /* Per-feature normalization then quantize to INT8 */
    float min_val =  1e9f, max_val = -1e9f;
    for (uint32_t i = 0; i < N_MEL; i++) {
        if (mel_float[i] < min_val) min_val = mel_float[i];
        if (mel_float[i] > max_val) max_val = mel_float[i];
    }
    float range = max_val - min_val + 1e-6f;
    for (uint32_t i = 0; i < N_MEL; i++) {
        float norm = (mel_float[i] - min_val) / range;   /* 0..1 */
        mel_int8[i] = (int8_t)(norm * 255.0f - 128.0f);  /* INT8 */
    }
}

/* ─────────────────────────────────────────────
   TFLM interpreter handle
   ───────────────────────────────────────────── */
#ifdef TFLM_AVAILABLE
static tflite::MicroInterpreter *s_interp = nullptr;
static TfLiteTensor             *s_input  = nullptr;
static TfLiteTensor             *s_output = nullptr;
#endif

/* ─────────────────────────────────────────────
   Public API
   ───────────────────────────────────────────── */
void wake_word_init(void) {
    fft_init();
    build_mel_filters();

    /* Build Hann window */
    volatile int16_t *hw = (volatile int16_t *)s_hann_win;
    for (uint32_t i = 0; i < WIN_SAMPLES; i++) {
        float w = 0.5f * (1.0f - cosf(2.0f * 3.14159265f * i / (WIN_SAMPLES - 1)));
        hw[i] = (int16_t)(w * 32767.0f);
    }

#ifdef TFLM_AVAILABLE
    const tflite::Model *model = tflite::GetModel(g_wake_word_model);

    static tflite::MicroMutableOpResolver<8> resolver;
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddBatchNorm();         /* via FULLY_CONNECTED op or custom */
    resolver.AddRelu();
    resolver.AddAveragePool2D();
    resolver.AddFullyConnected();
    resolver.AddSoftmax();
    resolver.AddReshape();

    static tflite::MicroInterpreter interpreter(
        model, resolver, s_tflm_arena, TFLM_ARENA_SIZE);

    s_interp = &interpreter;
    if (s_interp->AllocateTensors() != kTfLiteOk) {
        hal_fault("WW: tensor alloc failed");
    }
    s_input  = s_interp->input(0);
    s_output = s_interp->output(0);
#endif

    memset(s_mel_input, 0, sizeof(s_mel_input));
    s_frame_idx = 0;
}

/**
 * wake_word_process_audio()
 * Called every 10ms (HOP_SAMPLES = 160 new samples available).
 * Slides mel spectrogram window and runs inference when N_FRAMES accumulated.
 *
 * Returns: WW_RESULT_NONE or WW_RESULT_HEY_NITCH / WW_RESULT_QUICKNITCH
 */
ww_result_t wake_word_process_audio(void) {
    static int16_t s_pcm_buf[WIN_SAMPLES];
    static int32_t s_power[FFT_SIZE / 2 + 1];
    static float   s_mel_float[N_MEL];

    /* Get latest audio window (ring buffer copy) */
    hal_audio_get_window(s_pcm_buf);

    /* Compute power spectrum */
    compute_power_spectrum(s_pcm_buf, s_power);

    /* Apply mel filterbank */
    apply_mel_filterbank(s_power, s_mel_float);

    /* Quantize to INT8 and store in mel input buffer */
    int8_t mel_int8[N_MEL];
    mel_to_int8(s_mel_float, mel_int8);

    /* Shift mel spectrogram left by one frame (memmove) */
    memmove(s_mel_input, s_mel_input + N_MEL,
            (N_FRAMES - 1) * N_MEL * sizeof(int8_t));
    memcpy(s_mel_input + (N_FRAMES - 1) * N_MEL, mel_int8, N_MEL);

    s_frame_idx++;
    if (s_frame_idx < N_FRAMES) return WW_RESULT_NONE;
    /* Run inference every N_FRAMES/2 frames (50% overlap) for latency */
    if ((s_frame_idx % (N_FRAMES / 2)) != 0) return WW_RESULT_NONE;

#ifdef TFLM_AVAILABLE
    /* Copy mel input into TFLM input tensor */
    memcpy(s_input->data.int8, s_mel_input, N_FRAMES * N_MEL);

    if (s_interp->Invoke() != kTfLiteOk) return WW_RESULT_NONE;

    /* Softmax output: 10 classes, INT8
     * Class 0 = hey_nitch, Class 1 = quicknitch, rest = non-target */
    const int8_t *logits = s_output->data.int8;
    /* De-quantize with scale=1/256, zero_point=0 */
    float scores[10];
    for (int i = 0; i < 10; i++) {
        scores[i] = (float)(logits[i] + 128) / 255.0f;
    }

    /* Find argmax */
    float max_score = -1.0f;
    int   max_class = -1;
    for (int i = 0; i < 10; i++) {
        if (scores[i] > max_score) { max_score = scores[i]; max_class = i; }
    }

    /* Threshold: >0.90 to reduce false accepts */
    if (max_score < 0.90f) return WW_RESULT_NONE;

    if (max_class == 0) return WW_RESULT_HEY_NITCH;
    if (max_class == 1) return WW_RESULT_QUICKNITCH;
#endif

    return WW_RESULT_NONE;
}

/**
 * wake_word_build_i2c_msg()
 * Populate an I2C message for the detected wake word.
 */
void wake_word_build_i2c_msg(ww_result_t result, uint8_t conf_pct,
                              qn_i2c_msg_t *out) {
    out->header   = I2C_MSG_HEADER;
    out->msg_type = MSG_WAKE_WORD_DETECTED;
    memset(out->payload, 0, I2C_PAYLOAD_SIZE);

    qn_payload_wake_word_t *p = (qn_payload_wake_word_t *)out->payload;
    p->word_id        = (result == WW_RESULT_HEY_NITCH) ? 0 : 1;
    p->confidence_pct = conf_pct;
    p->noise_floor_dbfs = 0;  /* TODO: measure from PDM energy */

    out->crc16 = hal_crc16_ccitt((uint8_t *)out, I2C_MSG_SIZE - 2);
}
